plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Volumes/02-Raw FIles/Antigravity Projects/Krusti-web"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]